export const SITE_URL = 'https://trendmaxtr.com';
export const SITE_NAME = 'Trendmax';
export const DEFAULT_SOCIAL_IMAGE = '/hero/trendmax-corporate-operations-v1.webp';
export const DEFAULT_TITLE = 'Trendmax | E-Ticaret Yazılımı ve Entegrasyon Çözümleri';
export const DEFAULT_DESCRIPTION =
  'E-ticaret yazılımı, pazaryeri entegrasyonu, stoksuz satış, kurulum ve eğitim paketlerini Trendmax ile tek noktadan yönetin.';

/**
 * Tarama, sitemap, istemci meta etiketleri ve build sonu SEO kabukları için tek kaynak.
 * `schemaKind` yalnızca sayfadaki görünür ana içeriği tarif eder.
 */
export const STATIC_SEO_ROUTES = [
  {
    path: '/',
    label: 'Ana Sayfa',
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    schemaKind: 'home',
    changefreq: 'weekly',
    priority: '1.0',
  },
  {
    path: '/sss',
    label: 'Sıkça Sorulan Sorular',
    title: 'E-Ticaret Hakkında Sıkça Sorulan Sorular | Trendmax',
    description: 'Trendmax paketleri, ödeme, teslim, kurulum, entegrasyon ve pazaryeri eğitimleri hakkında sık sorulan soruların yanıtları.',
    schemaKind: 'faq',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/fiyatlar',
    label: 'Fiyatlar ve Paketler',
    title: 'E-Ticaret Paketleri ve Fiyatları | Trendmax',
    description: 'KDV dahil güncel Trendmax e-ticaret yazılımı, kurulum ve eğitim paketi fiyatlarını ve kapsamlarını karşılaştırın.',
    schemaKind: 'pricing',
    changefreq: 'weekly',
    priority: '0.9',
  },
  {
    path: '/kampus',
    label: 'Kampüs',
    title: 'E-Ticaret Rehberleri ve Eğitim İçerikleri | Trendmax Kampüs',
    description: 'E-ticaret, stoksuz satış, ürün araştırması, markalaşma ve dijital satış operasyonlarına yönelik rehberleri inceleyin.',
    schemaKind: 'collection',
    changefreq: 'weekly',
    priority: '0.8',
  },
  {
    path: '/cozumler',
    label: 'E-Ticaret Çözümleri',
    title: 'E-Ticaret Çözümleri | Trendmax',
    description: 'Hazır e-ticaret altyapısı, özel çözümler, pazaryeri kurulumu, stoksuz satış ve e-ihracat seçeneklerini inceleyin.',
    schemaKind: 'service',
    changefreq: 'monthly',
    priority: '0.9',
  },
  {
    path: '/cozumler/paketler',
    label: 'E-Ticaret Paketleri',
    title: 'Hazır E-Ticaret Yazılım Paketleri | Trendmax',
    description: 'Ürün, sipariş, kampanya, ödeme ve mağaza yönetimi özellikleri sunan Trendmax e-ticaret yazılım paketlerini inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Çözümler', path: '/cozumler' },
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/cozumler/premium',
    label: 'Premium E-Ticaret',
    title: 'Premium E-Ticaret Çözümleri | Trendmax',
    description: 'Gelişmiş mağaza yönetimi, entegrasyon ve özelleştirme ihtiyaçları için Trendmax Premium e-ticaret çözümünü inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Çözümler', path: '/cozumler' },
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/cozumler/ozel',
    label: 'Özel Çözümler',
    title: 'Özel E-Ticaret Yazılım Çözümleri | Trendmax',
    description: 'İş akışınıza göre planlanan özel e-ticaret yazılımı, entegrasyon ve proje geliştirme seçenekleri hakkında bilgi alın.',
    schemaKind: 'service',
    parent: { name: 'Çözümler', path: '/cozumler' },
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/cozumler/e-ihracat',
    label: 'E-İhracat',
    title: 'E-İhracat Yazılımı ve Global Satış Çözümleri | Trendmax',
    description: 'Çoklu dil, para birimi ve uluslararası satış kanallarına yönelik Trendmax e-ihracat çözümlerini inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Çözümler', path: '/cozumler' },
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/cozumler/sifir-risk',
    label: 'Sıfır Risk E-Ticaret',
    title: 'Sıfır Risk E-Ticaret Sitesi Paketi | Trendmax',
    description: 'Kurulum, hazır ürün kaynağı, eğitim ve operasyon bileşenlerini içeren Sıfır Risk E-Ticaret Sitesi Paketini inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Çözümler', path: '/cozumler' },
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/cozumler/pazar-yeri-pro',
    label: 'Pazar Yeri Pro Expert',
    title: 'Pazaryeri Kurulum ve Eğitim Paketi | Trendmax',
    description: 'Pazaryeri mağaza kurulumu, ürün yükleme, entegratör kullanımı ve operasyon eğitimlerini içeren paketi inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Çözümler', path: '/cozumler' },
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/entegrasyonlar',
    label: 'Entegrasyonlar',
    title: 'Pazaryeri, Kargo ve Sipariş Entegrasyonları | Trendmax',
    description: 'Pazaryeri, kargo, stok, fiyat, sipariş ve e-fatura süreçlerini tek panelden yönetmeye yardımcı olan entegrasyonları inceleyin.',
    schemaKind: 'service',
    changefreq: 'monthly',
    priority: '0.9',
  },
  {
    path: '/stoksuz-satis',
    label: 'Stoksuz Satış',
    title: 'Stoksuz Satış ve Dropshipping Çözümleri | Trendmax',
    description: 'XML ürün kaynağı, stok ve fiyat senkronizasyonu ile stoksuz e-ticaret operasyonuna yönelik çözümleri inceleyin.',
    schemaKind: 'service',
    changefreq: 'monthly',
    priority: '0.9',
  },
  {
    path: '/premium',
    label: 'Premium',
    title: 'Trendmax Premium E-Ticaret Özellikleri',
    description: 'Mobil uygulama, gelişmiş entegrasyon, SEO araçları ve sektörel tema seçenekleri sunan Trendmax Premium özelliklerini keşfedin.',
    schemaKind: 'service',
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/premium/mobil',
    label: 'Mobil Uygulama',
    title: 'E-Ticaret Mobil Uygulama Çözümü | Trendmax',
    description: 'Markanıza uyarlanabilen mobil mağaza deneyimi ve e-ticaret mobil uygulama özellikleri hakkında bilgi alın.',
    schemaKind: 'service',
    parent: { name: 'Premium', path: '/premium' },
    changefreq: 'monthly',
    priority: '0.6',
  },
  {
    path: '/premium/entegrasyon',
    label: 'Premium Entegrasyon',
    title: 'Gelişmiş E-Ticaret Entegrasyonları | Trendmax',
    description: 'Pazaryeri, ödeme, kargo ve operasyon sistemlerini bağlayan gelişmiş Trendmax entegrasyon seçeneklerini inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Premium', path: '/premium' },
    changefreq: 'monthly',
    priority: '0.6',
  },
  {
    path: '/premium/seo',
    label: 'SEO Özellikleri',
    title: 'E-Ticaret SEO Özellikleri | Trendmax',
    description: 'Ürün, kategori ve içerik sayfalarının arama motorları tarafından anlaşılmasına yardımcı olan e-ticaret SEO özelliklerini inceleyin.',
    schemaKind: 'service',
    parent: { name: 'Premium', path: '/premium' },
    changefreq: 'monthly',
    priority: '0.6',
  },
  {
    path: '/premium/temalar',
    label: 'E-Ticaret Temaları',
    title: 'Mobil Uyumlu E-Ticaret Tema Örnekleri | Trendmax',
    description: 'Farklı sektörlere yönelik masaüstü ve mobil e-ticaret tema örneklerini karşılaştırın.',
    schemaKind: 'collection',
    parent: { name: 'Premium', path: '/premium' },
    changefreq: 'monthly',
    priority: '0.7',
  },
  {
    path: '/referanslar',
    label: 'Tema ve Çözüm Örnekleri',
    title: 'E-Ticaret Tema ve Çözüm Örnekleri | Trendmax',
    description: 'Farklı sektörler için hazırlanan mağaza önizlemelerini, mobil deneyimi ve Trendmax tasarım yaklaşımını inceleyin.',
    schemaKind: 'collection',
    changefreq: 'monthly',
    priority: '0.6',
  },
  {
    path: '/hakkimizda',
    label: 'Hakkımızda',
    title: 'Trendmax Hakkında | E-Ticaret Teknolojileri',
    description: 'Trendmax e-ticaret yazılımı, entegrasyon, kurulum ve eğitim hizmetleri ile kurumsal iletişim bilgileri hakkında bilgi alın.',
    schemaKind: 'about',
    changefreq: 'monthly',
    priority: '0.8',
  },
  {
    path: '/iletisim',
    label: 'İletişim',
    title: 'Trendmax İletişim | Bursa Ofisi ve Destek Kanalları',
    description: 'Trendmax Bursa merkez adresi, telefon, e-posta, WhatsApp ve müşteri destek kanallarına ulaşın.',
    schemaKind: 'contact',
    changefreq: 'monthly',
    priority: '0.8',
  },
];

export const NOINDEX_SEO_ROUTES = [
  {
    path: '/odeme',
    title: 'Güvenli Ödeme | Trendmax',
    description: 'Trendmax paketiniz için PayTR güvenli ödeme adımı.',
  },
  {
    path: '/odeme-sonuc',
    title: 'Ödeme Sonucu | Trendmax',
    description: 'Trendmax sipariş ve ödeme durumu.',
  },
];

export const SEO_LAST_UPDATED = '2026-08-23';
